In [124]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

Concateno la media pesata dell'f1_score di ogni modello rispetto ad ogni emozione

In [125]:
csv_list = ['logistic_regression.csv','linear_SVM.csv','kernel_SVM.csv']
df_list = []

for csv in csv_list:
    df = pd.read_csv(csv, header=[0,1], index_col=[0,1])
    df_list.append(df)
    
for i, df in enumerate(df_list):
    df = df.drop(columns=['tilted','frontal'], level=1)
    df = df.drop(index='macro_avg', level=0).reset_index(level=0, drop=True)
    df_list[i] = df

df = pd.read_csv('LSTM.csv', index_col=[0,1], skiprows=[1])
df = df.drop(index='macro_avg', level=0).reset_index(level=0, drop=True)
df_list.append(df)

df = pd.concat(df_list, axis=1, sort=False)

columns_arrays = [
    ['logistic_regression','logistic_regression','logistic_regression','logistic_regression','linear_svm','linear_svm','linear_svm','linear_svm','kernel_svm','kernel_svm','kernel_svm','kernel_svm','lstm','lstm','lstm'],
    ['deluanay','au_intensities','au_activations','au_intensties_activations','deluanay','au_intensities','au_activations','au_intensties_activations','deluanay','au_intensities','au_activations','au_intensties_activations','au_intensities','au_activations','au_intensties_activations'],
    ['none']*15
]

columns_index = pd.MultiIndex.from_arrays(columns_arrays, names=['models', 'features', 'pose'])
index = ['anger','disgust','fear','happiness','sadness','surprise','valence']

df = pd.DataFrame(data=df.values, index=index, columns=columns_index)
df

models    logistic_regression                                \
features             deluanay au_intensities au_activations
pose                     none           none           none
anger                    0.57           0.57           0.63
disgust                  0.53           0.63           0.62
fear                     0.74           0.63           0.62
happiness                0.59           0.65           0.68
sadness                  0.55           0.56           0.62
surprise                 0.57           0.60           0.58
valence                  0.52           0.64           0.61

models                              linear_svm                                \
features  au_intensties_activations   deluanay au_intensities au_activations
pose                           none       none           none           none
anger                          0.60       0.58           0.63           0.63
disgust                        0.61       0.55           0.69           0.57
fear                           0.67       0.71           0.66           0.63
happiness                      0.65       0.61           0.66           0.66
sadness                        0.57       0.59           0.62           0.61
surprise                       0.62       0.57           0.58           0.56
valence                        0.63       0.54           0.62           0.61

models                              kernel_svm                                \
features  au_intensties_activations   deluanay au_intensities au_activations
pose                           none       none           none           none
anger                          0.65       0.55           0.61           0.59
disgust                        0.65       0.67           0.63           0.58
fear                           0.62       0.59           0.64           0.66
happiness                      0.65       0.52           0.55           0.66
sadness                        0.64       0.55           0.58           0.56
surprise                       0.61       0.50           0.55           0.55
valence                        0.60       0.48           0.52           0.63

models                                        lstm                 \
features  au_intensties_activations au_intensities au_activations
pose                           none           none           none
anger                          0.52           0.47           0.63
disgust                        0.55           0.49           0.42
fear                           0.57           0.79           0.68
happiness                      0.65           0.60           0.64
sadness                        0.51           0.49           0.66
surprise                       0.56           0.58           0.55
valence                        0.51           0.52           0.58

models
features  au_intensties_activations
pose                           none
anger                          0.57
disgust                        0.57
fear                           0.70
happiness                      0.64
sadness                        0.49
surprise                       0.59
valence                        0.60

Per ogni emozione evidenzio quale feature ha avuto il punteggio massimo in un determinato modello di ML

In [162]:
logistic_df = pd.read_csv('logistic_regression.csv', header=[0,1], index_col=[0,1])
logistic_df = logistic_df.drop(columns=['tilted','frontal'], level=1)
logistic_df = logistic_df.drop(index='macro_avg', level=0).reset_index(level=0, drop=True)
display(logistic_df.style.highlight_max(color='lightgreen', axis=1).format('{:.2f}'))

In [164]:
linear_df = pd.read_csv('linear_SVM.csv', header=[0,1], index_col=[0,1])
linear_df = linear_df.drop(columns=['tilted','frontal'], level=1)
linear_df = linear_df.drop(index='macro_avg', level=0).reset_index(level=0, drop=True)
linear_df.style.highlight_max(color='lightgreen', axis=1).format('{:.2f}')

In [165]:
kernel_df = pd.read_csv('kernel_SVM.csv', header=[0,1], index_col=[0,1])
kernel_df = kernel_df.drop(columns=['tilted','frontal'], level=1)
kernel_df = kernel_df.drop(index='macro_avg', level=0).reset_index(level=0, drop=True)
kernel_df.style.highlight_max(color='lightgreen', axis=1).format('{:.2f}')

In [166]:
lstm_df = pd.read_csv('LSTM.csv', header=0, index_col=[0,1], names=['au_intensities', 'au_activations', 'au_intensities_activations'], skiprows=[0])
lstm_df = lstm_df.drop(index='macro_avg', level=0).reset_index(level=0, drop=True)
lstm_df.style.highlight_max(color='lightgreen', axis=1).format('{:.2f}')

Tabella finale con lo score massimo di ogni modello

In [169]:
df_list = [logistic_df, linear_df, kernel_df, lstm_df]
max_values_list = []
for df in df_list:
    max_values_list.append(df.max(axis=1))

score_df = pd.concat(max_values_list, axis=1, sort=False)
score_df = score_df.T.rename(index={0:'logistic_regression', 1:'linear_SVM', 2:'kernel_SVM', 3:'LSTM'})
display(score_df.style.highlight_max(color = 'lightgreen').format('{:.2f}'))